# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# Location of the log file. For instance, `/var/log`.
logging:
  path: '/Users/zhangfan/Documents/log/common_log'
  register-shutdown-hook: true
