spring:
  datasource:
    druid:
      master: # 主数据源
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/root
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2: # 第二个数据源
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/user
        initialSize: 5
        minIdle: 5
        maxActive: 20