# 七牛云相关配置
qinNiuCloud:
  ACCESS_KEY: fm9bOrvx95CCHaxFmcwpA47OCtD5bQVRytaKjtvi
  SECRET_KEY: Nh6gW_xGhcawlPc-Z9Bzu3PU82vfh9q4FVn_2aTH
  bucketName: wechat_number
  bucketNameUrl: wechat.dustyblog.cn
  imgStyle: 自定义的图片样式（本文未用到）

# 上传图片的限制
upload:
  maxSize: 3.0