# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# Location of the log file. For instance, `/var/log`.
logging:
  path: '/Users/zhangfan/Documents/Git-public/Springboot-Home/log/common_log'
  # Register a shutdown hook for the logging system when it is initialized.
  register-shutdown-hook: true

logger_dao_level: '/Users/zhangfan/Documents/log/dao_log'