server:
  port: 8084
spring:
  datasource:
    # 主数据库
    master:
      password: master
      url: jdbc:mysql://47.98.178.84:3306/master?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: master
#      type: com.alibaba.druid.pool.DruidDataSource
    # 从数据库集群（可继续扩展）
    cluster:
    - key: slave1
      password: slave1
      url: jdbc:mysql://47.98.178.84:3306/slave1?useUnicode=true&characterEncoding=UTF-8
#      idle-timeout: 20000
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: slave1
#      type: com.alibaba.druid.pool.DruidDataSource
    - key: slave2
      password: slave2
      url: jdbc:mysql://47.98.178.84:3306/slave2?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: slave2
    druid:
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      # 配置获取连接等待超时的时间
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.van.mybatis.multipledata.entity
# mybatis sql 日志
logging:
  level:
    cn:
      van:
        mybatis:
          multipledata:
            mapper: debug