# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# Location of the log file. For instance, `/var/log`.
logging:
  path: /tmp/zhichu
  # Register a shutdown hook for the logging system when it is initialized.
  register-shutdown-hook: true

dubbo_zk_address: 192.168.10.223:2181
dubbo_cache: /tmp/zhichu/dubbo.cache
dubbo_port: -1
dubbo_register: false

###
server:
  port: 8083
  servlet:
    context-path: /zhichu2

### system ###
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver?view=sql-server-2017
    driverClassName: org.postgresql.Driver
    druid:
      url: jdbc:postgresql://pgm-wz9aelefxk9346edeo.pg.rds.aliyuncs.com:3432/zhichu
      username: javarw
      password: java2PJ88G7w4hQV4wREhqXcYZxYRCKU
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # https://stackoverflow.com/questions/10684244/dbcp-validationquery-for-different-databases
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #      stat-view-servlet:
      #        enabled: true
      #        url-pattern: /druid/*
      #        login-username: admin
      #        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  jackson:
    # One of the constants on Jackson's PropertyNamingStrategy
    # 跟原来.Net保持一致
    property-naming-strategy: UPPER_CAMEL_CASE

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sbt.zhichu.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
