spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: dev
    url: jdbc:mysql://47.98.178.84:3306/dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.van.mybatis.pageable.entity
logging:
  level:
    cn:
      van:
        mybatis:
          pageable:
            mapper: debug
